#!/bin/bash

CDEC_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
. $CDEC_DIR/env

if [ -z "$BOOST_VERSION" ]; then
	BOOST_VERSION="1.49.0"
fi

BOOST_VERSION_=$(echo $BOOST_VERSION | sed s/\\./_/g)
 
if [ ! -d $PREFIX/sw ]; then
	mkdir $PREFIX/sw
fi

if [ ! -f "$PREFIX/sw/boost_$BOOST_VERSION_.tar.gz" ]; then
	wget "http://sourceforge.net/projects/boost/files/boost/$BOOST_VERSION/boost_$BOOST_VERSION_.tar.gz/download" -O $PREFIX/sw/boost_$BOOST_VERSION_.tar.gz
fi

tar -xvzf $PREFIX/sw/boost_$BOOST_VERSION_.tar.gz -C $PREFIX/sw/

cd $PREFIX/sw/boost_$BOOST_VERSION_

./bootstrap.sh

./b2 install --prefix=$PREFIX
